### PR TITLE
Indicate broken repositories

### LINKED ISSUE #63: Improve error handling when a repository is incorrectly configured
We need to handle errors when a repository is incorrectly configured or when URL is incorrect.

## Definition of done
- [ ] A broken repository is clearly indicated to the user
- [ ] An external repository should be validated before it is available for selection

## Questions
- Should a broken repository be visible in the list but disabled?
- Should we download the complete repository and keep it cached locally in order to simplify things?

### PR DESCRIPTION
**Pull request by HenrikeW**
## Related Issues
This PR closes #63.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Changes

- show error message when no data can be fetched from a repository
- disable the broken repository in the selection list 

## Screenshot of the fix
image
image

## Testing

To test this, you will need to add a non-existing repository to your config file. 
- In `config.json` add this to the array of repositories:
```
    {
      "url": "broken-repo/root.json",
      "id": "broken-repo",
      "name": "Broken Repo"
    }
```
- Start the application and go to the home page
- Choose the repository called "Broken repository"
- The first time you choose it, you should see an error message
- Choose another repository
- Now the broken repository should be disabled in the list  

## Further comments
The repository will stay disabled as long as you stay on the Home page (you can open and close the side panel). As soon as you switch to Documentation, the repository will look available again.
This is not optimal but I think it can easily be solved in a future issue when we try to fetch all repository data on page load and cache it. I still think it's a relatively big improvement given the relatively small effort. 

## Checklist
- [x] Code builds and runs

### CODE REVIEW

File: src/components/ErrorMessage/ErrorMessage.tsx [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import "./ErrorMessage.css";
+
+export const ErrorMessage = () => {
+  return (
+    <div className="error-container">
+      <p>Oh no!</p>
+      <p>
+        We couln't fetch data from the chosen repository. <br></br> Please
```
Comment (pdmnyberg) [inline src/components/ErrorMessage/ErrorMessage.tsx]: "We couldn't.. "

**Review by pdmnyberg — CHANGES_REQUESTED** [review]
This is a good start. I think it will work well with my validation. I made a comment about spelling.

**Review by pdmnyberg — APPROVED** [review]
LGTM! Good start
